CREATE OR REPLACE PROCEDURE CURATED.LOG_APPLICATION_EVENT()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

INSERT INTO CURATED.APPLICATION_EVENT_LOG
(
    APPLICATION_ID,
    EVENT_TYPE
)
SELECT
    APPLICATION_ID,
    'APPLICATION_SUBMITTED'
FROM CURATED.APPLICATION_STREAM
WHERE METADATA$ACTION = 'INSERT';

RETURN 'EVENTS LOGGED';

END;
$$;