USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT JSON_FILE_FORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE
ALLOW_DUPLICATE = TRUE
STRIP_NULL_VALUES = FALSE;

-- APPLICATION DOCUMENTS

COPY INTO CURATED.APPLICATION_DOCUMENTS
(
    APPLICATION_ID,
    DOCUMENTS_JSON
)
FROM
(
    SELECT
        $1:APPLICATION_ID::NUMBER,
        $1
    FROM @RAW.RAW_STAGE/application_documents.json
)
FILE_FORMAT = (FORMAT_NAME = RAW.JSON_FILE_FORMAT);

-- SERVICE RULES

COPY INTO CURATED.SERVICE_RULES
(
    PROCESS_ID,
    RULE_CONFIG
)
FROM
(
    SELECT
        $1:PROCESS_ID::NUMBER,
        $1
    FROM @RAW.RAW_STAGE/service_rules.json
)
FILE_FORMAT = (FORMAT_NAME = RAW.JSON_FILE_FORMAT);

-- NOTIFICATION PAYLOADS

COPY INTO CURATED.NOTIFICATION_PAYLOADS
(
    NOTIFICATION_ID,
    PAYLOAD
)
FROM
(
    SELECT
        $1:NOTIFICATION_ID::NUMBER,
        $1
    FROM @RAW.RAW_STAGE/notification_payloads.json
)
FILE_FORMAT = (FORMAT_NAME = RAW.JSON_FILE_FORMAT);

-- USER ACTIVITY LOG

COPY INTO CURATED.USER_ACTIVITY_LOG
(
    USER_ID,
    ACTIVITY_TYPE,
    ACTIVITY_DATA
)
FROM
(
    SELECT
        $1:USER_ID::NUMBER,
        $1:ACTIVITY_TYPE::STRING,
        $1
    FROM @RAW.RAW_STAGE/user_activity_log.json
)
FILE_FORMAT = (FORMAT_NAME = RAW.JSON_FILE_FORMAT);