CREATE WAREHOUSE HAQ_SAHAYAK_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE HAQ_SAHAYAK_WH;

CREATE OR REPLACE DATABASE HAQ_SAHAYAK_DB;

USE DATABASE HAQ_SAHAYAK_DB;

CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA CURATED;
CREATE OR REPLACE SCHEMA ANALYTICS;