USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE DISTRICTS 
(
    DISTRICT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    DISTRICT_NAME VARCHAR(100) NOT NULL,
    STATE_NAME VARCHAR(100) NOT NULL
);