USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE OFFICES (
    OFFICE_ID NUMBER IDENTITY PRIMARY KEY,
    OFFICE_NAME VARCHAR(200) NOT NULL,
    OFFICE_TYPE VARCHAR(100) NOT NULL,
    DISTRICT_NAME VARCHAR(100) NOT NULL,
    STATE_CODE VARCHAR(10) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(200)
);