USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE PROCESSES 
 (
    PROCESS_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_NAME VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    URGENCY_LEVEL VARCHAR(20),
    COMPLEXITY_SCORE INTEGER,
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);
