USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE DOCUMENTS_REQUIRED 
(
    DOCUMENT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_ID INTEGER NOT NULL,
    DOCUMENT_NAME VARCHAR(200) NOT NULL,
    MANDATORY_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);