USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE LEGAL_LIMITS 
(
    LIMIT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_ID INTEGER NOT NULL,
    LEGAL_DAYS INTEGER NOT NULL,
    SOURCE_REFERENCE VARCHAR(500),
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);