USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE PROCESS_GUIDANCE 
(
    GUIDANCE_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_ID INTEGER NOT NULL,
    LANGUAGE_CODE VARCHAR(10) NOT NULL,
    STEP_NUMBER INTEGER NOT NULL,
    GUIDANCE_TEXT VARCHAR(5000) NOT NULL,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);