USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE ALTERNATIVE_PATHS 
(
    PATH_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_ID INTEGER NOT NULL,
    PATH_DESCRIPTION VARCHAR(5000) NOT NULL,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);