USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE CITIZEN_APPLICATIONS 
(
    APPLICATION_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_ID INTEGER NOT NULL,
    DISTRICT_ID INTEGER NOT NULL,
    APPLICANT_NAME VARCHAR(200) NOT NULL,
    SUBMISSION_DATE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    EXPECTED_COMPLETION_DATE DATE,
    ACTUAL_COMPLETION_DATE DATE,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);