USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE COMPLAINTS 
(
    COMPLAINT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    OFFICE_ID INTEGER NOT NULL,
    DISTRICT_ID INTEGER NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    COMPLAINT_TEXT VARCHAR(5000),
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);