USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE COMPLAINTS (
    COMPLAINT_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    OFFICE_ID NUMBER(38,0) NOT NULL,
    DISTRICT_ID NUMBER(38,0) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    COMPLAINT_TEXT VARCHAR(5000),
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);