USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;
CREATE OR REPLACE TABLE PROCESSING_TIMES 
(
    PROCESSING_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PROCESS_ID INTEGER NOT NULL,
    DISTRICT_ID INTEGER NOT NULL,
    AVERAGE_DAYS NUMBER(10,2) NOT NULL,
    MONTH_YEAR VARCHAR(20) NOT NULL,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);