USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE SERVICE_CATEGORIES 
(
    CATEGORY_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(500),
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);