USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CURATED.FAQS (
    FAQ_ID NUMBER IDENTITY PRIMARY KEY,
    QUESTION VARCHAR(1000) NOT NULL,
    ANSWER VARCHAR(5000) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);