USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE APPLICATION_AUDIT_LOG 
(
    AUDIT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    APPLICATION_ID INTEGER UNIQUE NOT NULL,
    OLD_STATUS VARCHAR(70),
    NEW_STATUS VARCHAR(70) NOT NULL,
    CHANGED_BY VARCHAR(150),
    CHANGE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    COMMENTS VARCHAR(1500)
);