USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE NOTIFICATIONS 
(
    NOTIFICATION_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    APPLICATION_ID INTEGER,
    NOTIFICATION_TYPE VARCHAR(170) NOT NULL,
    MESSAGE VARCHAR(6000) NOT NULL,
    STATUS VARCHAR(60) DEFAULT 'UNREAD STATUS....',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);