USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE DOCUMENT_VALIDATION_RULES 
(
    RULE_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    DOCUMENT_NAME VARCHAR(250) NOT NULL,
    VALIDATION_RULE VARCHAR(1200) NOT NULL,
    ERROR_MESSAGE VARCHAR(1200),
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);