USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE STATES 
(
    STATE_CODE VARCHAR(10) PRIMARY KEY,
    STATE_NAME VARCHAR(120) NOT NULL UNIQUE,
    REGION VARCHAR(50),
    CREATED_DATE DATE DEFAULT CURRENT_DATE()
);
