USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE APPLICATION_DOCUMENTS
(
    APPLICATION_ID NUMBER NOT NULL,
    DOCUMENTS_JSON VARIANT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);