USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE SERVICE_RULES
(
    RULE_ID NUMBER IDENTITY PRIMARY KEY,
    PROCESS_ID NUMBER,
    RULE_CONFIG VARIANT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);