USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CURATED.NOTIFICATION_PAYLOADS
(
    NOTIFICATION_ID NUMBER,
    PAYLOAD VARIANT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);