USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CURATED.USER_ACTIVITY_LOG
(
    ACTIVITY_ID NUMBER IDENTITY PRIMARY KEY,
    USER_ID NUMBER,
    ACTIVITY_TYPE VARCHAR(100),
    ACTIVITY_DATA VARIANT,
    ACTIVITY_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);