CREATE OR REPLACE VIEW VW_PROCESS_LEGAL_LIMITS
AS
SELECT
    P.PROCESS_ID,
    P.PROCESS_NAME,
    P.CATEGORY,
    L.LEGAL_DAYS,
    L.SOURCE_REFERENCE
FROM CURATED.PROCESSES P
INNER JOIN CURATED.LEGAL_LIMITS L
ON P.PROCESS_ID = L.PROCESS_ID;

CREATE OR REPLACE VIEW VW_DISTRICT_STATE
AS
SELECT
    D.DISTRICT_ID,
    D.DISTRICT_NAME,
    D.STATE_CODE,
    S.STATE_NAME,
    S.REGION
FROM CURATED.DISTRICTS D
INNER JOIN CURATED.STATES S
ON D.STATE_CODE = S.STATE_CODE;

CREATE OR REPLACE VIEW VW_PROCESS_RULES
AS
SELECT
    P.PROCESS_ID,
    P.PROCESS_NAME,
    S.RULE_CONFIG
FROM CURATED.PROCESSES P
INNER JOIN CURATED.SERVICE_RULES S
ON P.PROCESS_ID = S.PROCESS_ID;

CREATE OR REPLACE VIEW ANALYTICS.VW_USER_ACTIVITY_SUMMARY AS
SELECT
    USER_ID,
    COUNT(*) AS TOTAL_ACTIVITIES
FROM CURATED.USER_ACTIVITY_LOG
GROUP BY USER_ID;

CREATE OR REPLACE VIEW ANALYTICS.VW_SERVICE_RECOMMENDATIONS AS
SELECT
    PROCESS_ID,
    PROCESS_NAME,
    CATEGORY
FROM CURATED.PROCESSES
WHERE CATEGORY IN ('Certificate','Pension');