CREATE OR REPLACE VIEW ANALYTICS.VW_APPLICATION_TRACKING AS
SELECT
    A.APPLICATION_ID,
    A.APPLICANT_NAME,
    P.PROCESS_NAME,
    D.DISTRICT_NAME,
    A.STATUS,
    A.SUBMISSION_DATE
FROM CURATED.CITIZEN_APPLICATIONS A
INNER JOIN CURATED.PROCESSES P
ON A.PROCESS_ID = P.PROCESS_ID
INNER JOIN CURATED.DISTRICTS D
ON A.DISTRICT_ID = D.DISTRICT_ID;

CREATE OR REPLACE VIEW ANALYTICS.VW_NOTIFICATION_SUMMARY AS
SELECT
    N.NOTIFICATION_ID,
    A.APPLICANT_NAME,
    P.PROCESS_NAME,
    N.NOTIFICATION_TYPE,
    N.MESSAGE,
    N.CREATED_DATE
FROM CURATED.NOTIFICATIONS N
INNER JOIN CURATED.CITIZEN_APPLICATIONS A
ON N.APPLICATION_ID = A.APPLICATION_ID
INNER JOIN CURATED.PROCESSES P
ON A.PROCESS_ID = P.PROCESS_ID;