CREATE OR REPLACE VIEW ANALYTICS.VW_DASHBOARD_SUMMARY AS
SELECT
    (SELECT COUNT(*) FROM CURATED.CITIZEN_APPLICATIONS) AS TOTAL_APPLICATIONS,
    (SELECT COUNT(*) FROM CURATED.NOTIFICATIONS) AS TOTAL_NOTIFICATIONS,
    (SELECT COUNT(*) FROM CURATED.APPLICATION_EVENT_LOG) AS TOTAL_EVENTS,
    (SELECT COUNT(*) FROM CURATED.PROCESSES) AS TOTAL_SERVICES;