USE DATABASE HAQ_SAHAYAK_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE APPLICATION_EVENT_LOG
(
    EVENT_ID INTEGER AUTOINCREMENT,
    APPLICATION_ID INTEGER NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);